# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build doc
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      PY_PKG_NAME: stockbot
    steps:
      - uses: actions/checkout@v1
      - name: Build Sphinx doc
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: "pip install -r requirements.txt && pip install -r docs/requirements.txt"
          build-command: "sphinx-apidoc -o source/ ../$PY_PKG_NAME/ && make html"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html