# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests
on: [push]
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install TA-Lib
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make
          sudo make install

      - name: Test
        uses: onichandame/python-test-action@master
        env:
          SINOTRADE_ID: ${{ secrets.SINOTRADE_ID }}
          SINOTRADE_PASSWD: ${{ secrets.SINOTRADE_PASSWD }}
        with:
          deps_list: 'requirements.txt'
